ERROR_FAILED_TO_LOAD_CONFIG = 1
ERROR_FAILED_TO_READ_CONFIG = 2
ERROR_FAILED_TO_MAKE_SSL_CONTEXT = 3
ERROR_FAILED_TO_LOAD_MODULES = 4
ERROR_FAILED_TO_INITIALIZE_DATABASE = 5
ERROR_FAILED_TO_BIND_PORT = 6
ERROR_IP_IS_DEFAULT = 7
